(function(){
  const CRM=window.CRM=window.CRM||{},U=CRM.utils,S=CRM.state;
  let pendingFile=null,pendingWorkbook=null,pendingCandidates=[];
  const $=id=>document.getElementById(id);
  CRM.toast=function(message,type='success'){const el=U.dom('div',{class:`toast ${type}`,text:message,role:'status'});$('toastRegion').append(el);setTimeout(()=>el.remove(),3600)};
  function libraryReady(){return typeof XLSX!=='undefined'&&typeof echarts!=='undefined'}
  function selectFile(file){if(!file)return;const ext=file.name.split('.').pop()?.toLowerCase();if(!['xlsx','xls'].includes(ext)){CRM.toast('Please choose a valid .xlsx or .xls workbook.','error');return}pendingFile=file;$('selectedFileName').textContent=file.name;$('selectedFileMeta').textContent=U.formatBytes(file.size);$('selectedFile').hidden=false;$('dropZone').hidden=true}
  function resetSelection(){$('fileInput').value='';pendingFile=null;$('selectedFile').hidden=true;$('dropZone').hidden=false}
  function loader(stage,detail,percent){$('loaderStatus').textContent=stage;$('loaderDetail').textContent=detail;$('loaderProgress').style.width=`${percent}%`}
  function setView(name){$('landingView').hidden=name!=='landing';$('loaderView').hidden=name!=='loader';$('appShell').hidden=name!=='app'}
  async function analyze(){if(!pendingFile)return;if(!libraryReady()){CRM.toast('The Excel/chart libraries did not load. Internet access is required for the library files.','error');return}setView('loader');loader('Reading workbook','Opening the Excel file locally in your browser.',12);await tick(80);try{pendingWorkbook=await CRM.excel.readFile(pendingFile);loader('Detecting data','Inspecting worksheets and likely header rows.',28);await tick(100);pendingCandidates=CRM.excel.getSheetCandidates(pendingWorkbook);if(!pendingCandidates.length||pendingCandidates[0].score<0)throw new Error('No usable worksheet was detected.');if(pendingCandidates.length>1){showSheetPicker();setView('landing');return}await processSheet(pendingCandidates[0].name,pendingCandidates[0].headerRow)}catch(e){setView('landing');CRM.toast(e.message||'The workbook could not be analyzed.','error')}}
  function showSheetPicker(){const root=$('sheetList');root.replaceChildren();pendingCandidates.forEach((c,i)=>{const b=U.dom('button',{class:'sheet-option',type:'button'});const left=U.dom('div');left.append(U.dom('strong',{text:c.name}),U.dom('small',{text:`${U.formatNumber(c.rows)} rows · ${U.formatNumber(c.cols)} columns${i===0?' · recommended':''}`}));b.append(left,U.dom('span',{text:i===0?'Recommended':'Select'}));b.addEventListener('click',()=>{ $('sheetModal').hidden=true;setView('loader');processSheet(c.name,c.headerRow).catch(err=>{setView('landing');CRM.toast(err.message,'error')})});root.append(b)});$('sheetModal').hidden=false}
  async function processSheet(sheetName,headerRow){loader('Profiling columns','Detecting data types, completeness and cardinality.',45);await tick(80);const parsed=CRM.excel.parseSheet(pendingWorkbook,sheetName,headerRow);S.file=pendingFile;S.workbook=pendingWorkbook;S.sheetNames=pendingWorkbook.SheetNames;S.currentSheet=sheetName;S.rawRows=parsed.rows;S.rows=parsed.rows;S.columns=parsed.headers;S.headerRow=parsed.headerRow;S.datasetName=pendingFile.name;S.loadedAt=new Date();loader('Detecting CRM dimensions','Matching representatives, customers, dates, locations and opportunity fields.',62);await tick(80);S.profile=CRM.profiler.profile(S.rows,S.columns);S.mappings=CRM.profiler.mapSemantics(S.rows,S.profile);S.duplicateRows=CRM.profiler.detectDuplicateRows(S.rows,S.columns);S.filters={};S.dateFilter=null;S.searchQuery='';S.filteredRows=[...S.rows];S.visibleColumns=new Set(S.columns);S.pagination={page:1,rowsPerPage:25};S.sort={column:null,direction:'asc'};S.activeSection='overview';loader('Building analytics','Creating metrics, rankings and interconnected filters.',78);await tick(100);loader('Preparing dashboard','Rendering the analytics workspace and quality checks.',94);await tick(130);$('datasetName').textContent=S.datasetName;setView('app');CRM.dashboard.renderAll();CRM.dashboard.renderFilters();CRM.dashboard.datePresetButtons();loader('Ready','Dashboard prepared.',100);CRM.toast(`${U.formatNumber(S.rows.length)} records loaded successfully.`,'success');setTimeout(CRM.charts.resizeAll,180)}
  function tick(ms=0){return new Promise(r=>setTimeout(r,ms))}
  function openFilters(){$('filterDrawer').hidden=false;CRM.dashboard.renderFilters();CRM.dashboard.datePresetButtons()}
  function closeFilters(){$('filterDrawer').hidden=true}
  function exportRows(rows,cols,name){if(!rows.length){CRM.toast('There are no records to export.','error');return}U.downloadText(U.csvFromRows(rows,cols),name);CRM.toast('CSV export created.','success')}
  function closeModalById(id){const el=$(id);if(el)el.hidden=true}
  function bind(){
    $('dropZone').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>selectFile(e.target.files?.[0]));
    ['dragenter','dragover'].forEach(ev=>$('dropZone').addEventListener(ev,e=>{e.preventDefault();$('dropZone').classList.add('is-dragging')}));['dragleave','drop'].forEach(ev=>$('dropZone').addEventListener(ev,e=>{e.preventDefault();$('dropZone').classList.remove('is-dragging')}));$('dropZone').addEventListener('drop',e=>selectFile(e.dataTransfer.files?.[0]));
    $('changeFileBtn').addEventListener('click',resetSelection);$('analyzeBtn').addEventListener('click',analyze);$('replaceDatasetBtn').addEventListener('click',()=>{setView('landing');resetSelection();window.scrollTo(0,0)});
    $('openFiltersBtn').addEventListener('click',openFilters);$('closeFiltersBtn').addEventListener('click',closeFilters);$('drawerDoneBtn').addEventListener('click',closeFilters);$('drawerClearBtn').addEventListener('click',()=>CRM.filters.clearAll());$('clearAllBtn').addEventListener('click',()=>CRM.filters.clearAll());
    $('detailDrawerBackdrop').addEventListener('click',e=>{if(e.target===$('detailDrawerBackdrop'))$('detailDrawerBackdrop').hidden=true});$('closeDetailBtn').addEventListener('click',()=>$('detailDrawerBackdrop').hidden=true);
    $('filterDrawer').addEventListener('click',()=>{});$('filterDrawer').parentElement?.addEventListener('click',e=>{if(e.target===$('filterDrawer'))closeFilters()});
    $('configureFieldsBtn').addEventListener('click',()=>{CRM.dashboard.renderFieldMappings();$('fieldsModal').hidden=false});$('saveMappingsBtn').addEventListener('click',CRM.dashboard.saveFieldMappings);
    document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModalById(b.dataset.closeModal)));
    $('columnSelectorBtn').addEventListener('click',()=>{CRM.table.renderColumnSelector();$('columnModal').hidden=false});
    $('exportFilteredBtn').addEventListener('click',()=>exportRows(S.filteredRows,S.columns,`crm-filtered-${new Date().toISOString().slice(0,10)}.csv`));$('exportTableBtn').addEventListener('click',()=>exportRows(S.filteredRows,CRM.table.getVisible(),`crm-visible-${new Date().toISOString().slice(0,10)}.csv`));
    $('globalSearchBtn').addEventListener('click',openSearch);$('globalSearchInput').addEventListener('input',U.debounce(CRM.dashboard.renderSearchPreview,100));
    $('mobileMenuBtn').addEventListener('click',()=>document.body.classList.toggle('sidebar-open'));$('collapseSidebarBtn').addEventListener('click',()=>document.body.classList.toggle('sidebar-collapsed'));
    $('academyCta').addEventListener('click',async()=>{const text='I would like to discuss building a custom business dashboard with X Academy.';try{await navigator.clipboard.writeText(text);CRM.toast('Dashboard inquiry text copied.','success')}catch(e){CRM.toast('X Academy — Learn. Analyse. Lead.','success')}});
    document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();openSearch()}if(e.key==='Escape'){['searchModal','sheetModal','fieldsModal','columnModal'].forEach(closeModalById);$('detailDrawerBackdrop').hidden=true;closeFilters()}});
    document.querySelectorAll('.modal-backdrop').forEach(back=>back.addEventListener('click',e=>{if(e.target===back)back.hidden=true}));
  }
  function openSearch(){$('searchModal').hidden=false;$('globalSearchInput').value=S.searchQuery||'';CRM.dashboard.renderSearchPreview();setTimeout(()=>$('globalSearchInput').focus(),10)}
  window.addEventListener('DOMContentLoaded',()=>{bind();setView('landing');setTimeout(()=>{if(typeof XLSX==='undefined')CRM.toast('Excel parsing library has not loaded yet. An internet connection is required on first load.','error')},3000)});
})();
