(function(){
  const CRM=window.CRM=window.CRM||{},U=CRM.utils;
  const palette=['#9A78FF','#FF846D','#F1B15D','#67D4A7','#BBA7FF','#D68BFF','#7AA8FF','#C6D36A'];
  function ensure(){return typeof echarts!=='undefined'}
  function base(){return{animationDuration:420,animationEasing:'cubicOut',textStyle:{fontFamily:'Inter, Almarai, sans-serif',color:'#d9d2e1'},tooltip:{trigger:'axis',backgroundColor:'#1a1522',borderColor:'#352b42',textStyle:{color:'#f3eff7',fontSize:10},extraCssText:'box-shadow:0 10px 30px rgba(0,0,0,.28);border-radius:10px;'},grid:{left:42,right:16,top:24,bottom:34,containLabel:true}}}
  function dispose(id){const el=document.getElementById(id);if(el&&ensure()){const inst=echarts.getInstanceByDom(el);if(inst)inst.dispose()}CRM.state.charts.delete(id)}
  function mount(id,option,onClick){const el=document.getElementById(id);if(!el||!ensure())return null;dispose(id);const chart=echarts.init(el,null,{renderer:'canvas'});chart.setOption(option);if(onClick)chart.on('click',onClick);CRM.state.charts.set(id,chart);return chart}
  function axisStyle(){return{axisLine:{lineStyle:{color:'#2b2435'}},axisTick:{show:false},axisLabel:{color:'#81798b',fontSize:9},splitLine:{lineStyle:{color:'#211a2a'}}}}
  function horizontalBar(id,data,column,valueLabel='Records',isMoney=false){const items=data.slice(0,10);const max=Math.max(...items.map(x=>x[1]),1);const option={...base(),grid:{left:10,right:18,top:8,bottom:20,containLabel:true},xAxis:{type:'value',...axisStyle(),axisLabel:{color:'#81798b',fontSize:9,formatter:v=>isMoney?U.compactNumber(v):U.formatNumber(v)}},yAxis:{type:'category',data:items.map(x=>x[0]).reverse(),...axisStyle(),axisLabel:{color:'#aaa1b4',fontSize:9,width:130,overflow:'truncate'}},series:[{type:'bar',data:items.map((x,i)=>({value:x[1],itemStyle:{color:i===0?palette[0]:'#4b3d62'}})).reverse(),barWidth:12,itemStyle:{borderRadius:[0,5,5,0]},label:{show:true,position:'right',color:'#b8afc2',fontSize:9,formatter:p=>isMoney?U.compactNumber(p.value):U.formatNumber(p.value)}}],tooltip:{...base().tooltip,formatter:p=>`${p[0].name}<br/><b>${valueLabel}: ${isMoney?U.formatNumber(p[0].value):U.formatNumber(p[0].value)}</b>`}};return mount(id,option,e=>CRM.filters.setSingle(column,e.name,'chart'))}
  function donut(id,data,column){const items=data.slice(0,8);const option={...base(),tooltip:{...base().tooltip,trigger:'item',formatter:p=>`${p.name}<br/><b>${U.formatNumber(p.value)} records</b> · ${p.percent}%`},legend:{bottom:0,left:'center',textStyle:{color:'#81798b',fontSize:9},itemWidth:8,itemHeight:8,type:'scroll'},series:[{type:'pie',radius:['50%','72%'],center:['50%','44%'],padAngle:2,itemStyle:{borderColor:'#141019',borderWidth:3,borderRadius:4},label:{show:false},data:items.map((x,i)=>({name:x[0],value:x[1],itemStyle:{color:palette[i%palette.length]}}))}]};return mount(id,option,e=>CRM.filters.setSingle(column,e.name,'chart'))}
  function timeline(id,rows,dateCol){const by=new Map();rows.forEach(r=>{const d=U.parseDate(r[dateCol]);if(!d)return;const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;by.set(key,(by.get(key)||0)+1)});const arr=[...by.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const option={...base(),xAxis:{type:'category',boundaryGap:false,data:arr.map(x=>x[0]),...axisStyle(),axisLabel:{color:'#81798b',fontSize:9,formatter:v=>v.slice(5)}},yAxis:{type:'value',minInterval:1,...axisStyle()},series:[{type:'line',data:arr.map(x=>x[1]),smooth:.35,symbol:'circle',symbolSize:5,lineStyle:{width:3,color:palette[0]},itemStyle:{color:palette[2],borderColor:'#141019',borderWidth:2},areaStyle:{color:{type:'linear',x:0,y:0,x2:0,y2:1,colorStops:[{offset:0,color:'rgba(154,120,255,.28)'},{offset:1,color:'rgba(154,120,255,0)'}]}}}]};return mount(id,option,e=>{const d=U.parseDate(e.name);if(d)CRM.filters.setDate(d,d,'Chart date')})}
  function moneyTimeline(id,rows,dateCol,amountCol){const by=new Map();rows.forEach(r=>{const d=U.parseDate(r[dateCol]),v=U.numberValue(r[amountCol]);if(!d||!Number.isFinite(v))return;const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;by.set(key,(by.get(key)||0)+v)});const arr=[...by.entries()].sort((a,b)=>a[0].localeCompare(b[0]));const option={...base(),xAxis:{type:'category',boundaryGap:false,data:arr.map(x=>x[0]),...axisStyle(),axisLabel:{color:'#81798b',fontSize:9,formatter:v=>v.slice(5)}},yAxis:{type:'value',...axisStyle(),axisLabel:{color:'#81798b',fontSize:9,formatter:U.compactNumber}},series:[{type:'bar',data:arr.map(x=>x[1]),barMaxWidth:24,itemStyle:{color:palette[1],borderRadius:[5,5,0,0]}}]};return mount(id,option)}
  function heatmap(id,rows,dateCol){const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],hours=[...Array(24)].map((_,i)=>String(i));const map=new Map();rows.forEach(r=>{const d=U.parseDate(r[dateCol]);if(!d)return;const k=`${d.getDay()}-${d.getHours()}`;map.set(k,(map.get(k)||0)+1)});const data=[];for(let day=0;day<7;day++)for(let h=0;h<24;h++)data.push([h,day,map.get(`${day}-${h}`)||0]);const max=Math.max(...data.map(x=>x[2]),1);const option={...base(),grid:{left:38,right:12,top:8,bottom:35,containLabel:true},tooltip:{...base().tooltip,position:'top',formatter:p=>`${days[p.value[1]]} ${String(p.value[0]).padStart(2,'0')}:00<br/><b>${p.value[2]} visits</b>`},xAxis:{type:'category',data:hours,...axisStyle(),splitArea:{show:true,areaStyle:{color:['#141019','#15111c']}}},yAxis:{type:'category',data:days,...axisStyle(),splitArea:{show:true}},visualMap:{min:0,max,calculable:false,orient:'horizontal',left:'center',bottom:0,inRange:{color:['#211a2b','#4a366c','#9A78FF']},textStyle:{color:'#81798b',fontSize:8},itemWidth:80,itemHeight:6},series:[{type:'heatmap',data,label:{show:false},itemStyle:{borderRadius:3,borderWidth:2,borderColor:'#141019'}}]};return mount(id,option)}
  function resizeAll(){CRM.state.charts.forEach(c=>c.resize())}
  window.addEventListener('resize',U.debounce(resizeAll,120));
  CRM.charts={horizontalBar,donut,timeline,moneyTimeline,heatmap,dispose,resizeAll};
})();
