(function(){
  const CRM=window.CRM=window.CRM||{},U=CRM.utils;
  const icons={overview:'◇',activity:'⌁',customers:'◎',representatives:'◉',opportunities:'↗',locations:'⌖',quality:'◫',explorer:'≣'};
  const labels={overview:'Overview',activity:'Activity',customers:'Customers',representatives:'Representatives',opportunities:'Opportunities',locations:'Locations',quality:'Data Quality',explorer:'Data Explorer'};
  function has(c){return !!CRM.state.mappings[c]}
  function availableSections(){const out=['overview'];if(has('date')||has('purpose'))out.push('activity');if(has('customer')||has('company'))out.push('customers');if(has('representative'))out.push('representatives');if(has('amount'))out.push('opportunities');if(has('location'))out.push('locations');out.push('quality','explorer');return out}
  function renderNav(){const nav=document.getElementById('sideNav');nav.replaceChildren();availableSections().forEach(s=>{const b=U.dom('button',{class:`nav-item ${CRM.state.activeSection===s?'is-active':''}`,type:'button'});b.append(U.dom('span',{text:icons[s]}),U.dom('span',{text:labels[s]}));b.addEventListener('click',()=>showSection(s));nav.append(b)})}
  function showSection(name){CRM.state.activeSection=name;document.querySelectorAll('.dashboard-section').forEach(s=>s.hidden=s.dataset.section!==name);renderNav();document.body.classList.remove('sidebar-open');if(name==='explorer')CRM.table.render();else renderSection(name);window.scrollTo({top:0,behavior:'smooth'});setTimeout(CRM.charts.resizeAll,30)}
  function meaningfulCount(col,rows=CRM.state.filteredRows){if(!col)return 0;return rows.reduce((n,r)=>n+(!U.isBlank(r[col])?1:0),0)}
  function uniqueCount(col,rows=CRM.state.filteredRows){if(!col)return 0;return new Set(rows.map(r=>U.cleanText(r[col])).filter(Boolean)).size}
  function amountValues(rows=CRM.state.filteredRows){const c=CRM.state.mappings.amount;return c?rows.map(r=>U.numberValue(r[c])).filter(Number.isFinite):[]}
  function previousPeriodRows(){const S=CRM.state,dc=S.mappings.date;if(!dc||!S.dateFilter?.start||!S.dateFilter?.end)return null;const duration=S.dateFilter.end.getTime()-S.dateFilter.start.getTime()+86400000;const end=new Date(S.dateFilter.start.getTime()-86400000),start=new Date(end.getTime()-duration+86400000);return S.rows.filter(r=>{const d=U.parseDate(r[dc]);return d&&d>=start&&d<=end})}
  function makeKpi(label,value,sub,icon='◇',emphasis=false,trend=null,title=''){const a=U.dom('article',{class:`kpi-card ${emphasis?'emphasis':''}`,title});const top=U.dom('div',{class:'kpi-top'});top.append(U.dom('span',{text:label}),U.dom('span',{class:'kpi-icon',text:icon}));a.append(top,U.dom('strong',{class:'kpi-value',text:value}),U.dom('span',{class:'kpi-sub',text:sub||''}));if(trend&&Number.isFinite(trend.value)){const t=U.dom('span',{class:`kpi-trend ${trend.value<0?'down':''}`,text:`${trend.value>=0?'↑':'↓'} ${Math.abs(trend.value).toFixed(1)}% ${trend.label||'vs previous period'}`});a.append(t)}return a}
  function calcTrend(current,prev){if(!Number.isFinite(current)||!Number.isFinite(prev)||prev===0)return null;return{value:(current-prev)/Math.abs(prev)*100,label:'vs previous period'}}
  function renderKpis(){const root=document.getElementById('kpiGrid'),S=CRM.state,R=S.filteredRows,M=S.mappings;root.replaceChildren();const prev=previousPeriodRows();const list=[];list.push(makeKpi('Total Records',U.formatNumber(R.length),`${U.formatNumber(S.rows.length)} in dataset`,'≣',true,prev?calcTrend(R.length,prev.length):null,'Number of records matching current filters.'));
    if(M.customer)list.push(makeKpi('Unique Customers',U.formatNumber(uniqueCount(M.customer)),`${meaningfulCount(M.customer)} populated records`,'◎',true,null,'Distinct customer names in the current result set.'));
    if(M.company&&M.company!==M.customer)list.push(makeKpi('Projects / Companies',U.formatNumber(uniqueCount(M.company)),`${meaningfulCount(M.company)} populated`,'▦'));
    if(M.representative)list.push(makeKpi('Active Representatives',U.formatNumber(uniqueCount(M.representative)),`${U.formatNumber(R.length/Math.max(1,uniqueCount(M.representative)),1)} avg records / rep`,'◉'));
    if(M.amount){const vals=amountValues();if(vals.length){const total=vals.reduce((a,b)=>a+b,0),prevVals=prev?prev.map(r=>U.numberValue(r[M.amount])).filter(Number.isFinite):[];list.push(makeKpi('Opportunity Potential',U.compactNumber(total),`${vals.length} valued of ${R.length} records`,'↗',true,prevVals.length?calcTrend(total,prevVals.reduce((a,b)=>a+b,0)):null,'Expected amount / opportunity potential. This is not actual revenue.'));list.push(makeKpi('Average Expected Amount',U.compactNumber(total/vals.length),`Median ${U.compactNumber(U.median(vals))}`,'∿'))}}
    if(M.location)list.push(makeKpi('Locations Covered',U.formatNumber(uniqueCount(M.location)),`${meaningfulCount(M.location)} populated records`,'⌖'));
    if(M.purpose)list.push(makeKpi('Visit Purposes',U.formatNumber(uniqueCount(M.purpose)),`${meaningfulCount(M.purpose)} categorized`,'⌁'));
    if(M.issue){const n=meaningfulCount(M.issue);if(n)list.push(makeKpi('Records with Issues',U.formatNumber(n),`${U.formatPercent(n/Math.max(1,R.length)*100,1)} of matching records`,'!'))}
    if(M.product){const n=meaningfulCount(M.product);if(n)list.push(makeKpi('Product Requests',U.formatNumber(n),`${uniqueCount(M.product)} distinct entries`,'□'))}
    list.slice(0,10).forEach(x=>root.append(x));
  }
  function topValue(col,rows=CRM.state.filteredRows){const arr=col?U.groupCount(rows,col):[];return arr[0]||null}
  function renderHighlights(){const root=document.getElementById('insightsGrid'),S=CRM.state,R=S.filteredRows,M=S.mappings;root.replaceChildren();const insight=U.dom('article',{class:'insight-card'});insight.append(U.dom('h3',{text:'Data Highlights'}));const list=U.dom('div',{class:'highlight-list'}),items=[];
    if(M.representative){const x=topValue(M.representative);if(x)items.push(['Highest visit count',x[0],`${x[1]} records`])}
    if(M.purpose){const x=topValue(M.purpose);if(x)items.push(['Most common purpose',x[0],`${x[1]} records`])}
    if(M.location){const x=topValue(M.location);if(x)items.push(['Most active location',x[0],`${x[1]} records`])}
    if(M.issue){const n=meaningfulCount(M.issue);items.push(['Issue-record share',U.formatPercent(n/Math.max(R.length,1)*100,1),`${n} records contain issues`])}
    if(M.customer){const counts=U.groupCount(R,M.customer),repeat=counts.filter(x=>x[1]>1).length;items.push(['Repeat customers',U.formatNumber(repeat),`${U.formatPercent(repeat/Math.max(1,counts.length)*100,1)} of identified customers`])}
    if(M.amount){const vals=amountValues();if(vals.length)items.push(['Highest opportunity',U.compactNumber(Math.max(...vals)),`${vals.length} records contain expected amount`])}
    if(M.date){const arr=U.groupCount(R.map(r=>({...r,__day:U.formatDate(r[M.date])})),'__day');if(arr[0])items.push(['Busiest day',arr[0][0],`${arr[0][1]} records`])}
    items.slice(0,6).forEach(([k,v,s])=>{const x=U.dom('div',{class:'highlight-item'});x.append(U.dom('span',{text:k}),U.dom('strong',{text:v}),U.dom('small',{text:s}));list.append(x)});if(!items.length)list.append(U.dom('div',{class:'empty-card',text:'More highlights will appear when the dataset contains useful dimensions.'}));insight.append(list);
    const quality=U.dom('article',{class:'quality-summary'});quality.append(U.dom('h3',{text:'Data Quality Snapshot'}));const avg=S.profile.length?S.profile.reduce((sum,p)=>sum+(100-p.missingPct),0)/S.profile.length:0;[['Overall completeness',avg],['Columns with ≥90% missing',S.profile.filter(p=>p.missingPct>=90).length/S.profile.length*100],['Duplicate row rate',S.rows.length?S.duplicateRows/S.rows.length*100:0]].forEach(([label,pct],i)=>{const row=U.dom('div',{class:'quality-mini'});row.append(U.dom('span',{text:label}),U.dom('b',{text:i===1?`${S.profile.filter(p=>p.missingPct>=90).length} columns`:i===2?`${S.duplicateRows} rows`:U.formatPercent(pct,1)}));const tr=U.dom('div',{class:'quality-track'});tr.append(U.dom('i',{style:`width:${Math.max(0,Math.min(100,i?100-pct:pct))}%`}));row.append(tr);quality.append(row)});root.append(insight,quality)
  }
  function chartCard(title,subtitle,id,cls=''){const card=U.dom('article',{class:`chart-card ${cls}`});const head=U.dom('div',{class:'chart-head'}),copy=U.dom('div');copy.append(U.dom('h3',{text:title}),U.dom('p',{text:subtitle}));head.append(copy,U.dom('span',{class:'chart-badge',text:'Click to filter'}));card.append(head,U.dom('div',{class:'chart-canvas',id}));return card}
  function renderOverviewCharts(){const root=document.getElementById('chartGrid'),S=CRM.state,R=S.filteredRows,M=S.mappings;root.replaceChildren();let n=0;
    if(M.date&&R.some(r=>U.parseDate(r[M.date]))){root.append(chartCard('Activity over time','Records by visit date','chartTimeline','wide'));setTimeout(()=>CRM.charts.timeline('chartTimeline',R,M.date),0);n++}
    if(M.representative&&uniqueCount(M.representative)>1){root.append(chartCard('Visits by representative','Activity count, not sales performance','chartRep','compact'));setTimeout(()=>CRM.charts.horizontalBar('chartRep',U.groupCount(R,M.representative),M.representative,'Records'),0);n++}
    if(M.location&&uniqueCount(M.location)>1){root.append(chartCard('Activity by location','Distribution across detected locations','chartLocation'));setTimeout(()=>CRM.charts.donut('chartLocation',U.groupCount(R,M.location),M.location),0);n++}
    if(M.purpose&&uniqueCount(M.purpose)>1){root.append(chartCard('Purpose of visit','Current visit-purpose mix','chartPurpose'));setTimeout(()=>CRM.charts.donut('chartPurpose',U.groupCount(R,M.purpose),M.purpose),0);n++}
    if(M.amount&&M.representative&&amountValues().length){root.append(chartCard('Opportunity potential by representative','Expected amount; not actual revenue','chartAmountRep','wide'));setTimeout(()=>CRM.charts.horizontalBar('chartAmountRep',U.groupSum(R,M.representative,M.amount),M.representative,'Expected Amount',true),0);n++}
    const cust=M.customer||M.company;if(cust&&uniqueCount(cust)>1){root.append(chartCard('Top customers / accounts','Ranked by interaction volume','chartCustomers','compact'));setTimeout(()=>CRM.charts.horizontalBar('chartCustomers',U.groupCount(R,cust),cust,'Records'),0);n++}
    if(!n){const e=U.dom('article',{class:'chart-card wide'});e.append(U.dom('div',{class:'empty-card',text:'No suitable chart dimensions were detected. Your data remains available in Data Explorer.'}));root.append(e)}
  }
  function renderOverview(){renderKpis();renderHighlights();renderOverviewCharts()}
  function renderActivity(){const root=document.getElementById('activityContent'),S=CRM.state,R=S.filteredRows,M=S.mappings;root.replaceChildren();const grid=U.dom('div',{class:'analytics-grid'});if(M.date){const card=chartCard('Visit activity heatmap','Day-of-week and hour distribution','activityHeat');card.className='chart-card wide';grid.append(card);setTimeout(()=>CRM.charts.heatmap('activityHeat',R,M.date),0)}if(M.purpose){const card=chartCard('Purpose distribution','Click a segment to filter','activityPurpose');card.className='chart-card compact';grid.append(card);setTimeout(()=>CRM.charts.donut('activityPurpose',U.groupCount(R,M.purpose),M.purpose),0)}const noteCols=[M.notes,M.issue].filter(Boolean);if(noteCols.length){const p=U.dom('article',{class:'text-panel'});p.append(U.dom('h3',{text:'Common terms in notes & issues'}));const terms=U.topTerms(R,noteCols,18),wrap=U.dom('div',{class:'active-chips'});terms.forEach(([w,c])=>wrap.append(U.dom('span',{class:'filter-chip',text:`${w} · ${c}`})));if(!terms.length)wrap.append(U.dom('span',{class:'kpi-sub',text:'Not enough text content for a meaningful term summary.'}));p.append(wrap);grid.append(p)}root.append(grid)}
  function entityRankingContent(groupCol){const R=CRM.state.filteredRows,M=CRM.state.mappings,rows=U.groupCount(R,groupCol).slice(0,30),max=rows[0]?.[1]||1;const panel=U.dom('article',{class:'ranking-panel'}),table=U.dom('table',{class:'ranking-table'}),thead=U.dom('thead'),trh=U.dom('tr');['Entity','Records','Share',''].forEach(x=>trh.append(U.dom('th',{text:x})));thead.append(trh);table.append(thead);const tb=U.dom('tbody');rows.forEach(([name,count])=>{const tr=U.dom('tr');const share=count/Math.max(1,R.length)*100;const bar=U.dom('div',{class:'rank-bar'});bar.append(U.dom('span',{style:`width:${count/max*100}%`}));tr.append(U.dom('td',{text:name}),U.dom('td',{text:U.formatNumber(count)}),U.dom('td',{text:U.formatPercent(share,1)}),U.dom('td',{},bar));tr.addEventListener('click',()=>CRM.filters.setSingle(groupCol,name,'ranking'));tb.append(tr)});table.append(tb);panel.append(table);return panel}
  function renderRepresentatives(){const root=document.getElementById('representativesContent'),S=CRM.state,R=S.filteredRows,M=S.mappings;root.replaceChildren();if(!M.representative)return;const grid=U.dom('div',{class:'analytics-grid'}),metric=U.dom('article',{class:'metric-panel'}),pk=U.dom('div',{class:'panel-kpis'});const reps=uniqueCount(M.representative);[['Representatives',reps],['Avg records / rep',reps?R.length/reps:0],['Unique customers',M.customer?uniqueCount(M.customer):0],['Locations',M.location?uniqueCount(M.location):0]].forEach(([l,v])=>{const a=U.dom('article');a.append(U.dom('span',{text:l}),U.dom('strong',{text:Number.isInteger(v)?U.formatNumber(v):U.formatNumber(v,1)}));pk.append(a)});metric.append(pk);grid.append(metric,entityRankingContent(M.representative));if(M.amount&&amountValues().length){const c=chartCard('Expected amount by representative','Opportunity potential only','repMoney');c.className='chart-card wide';grid.append(c);setTimeout(()=>CRM.charts.horizontalBar('repMoney',U.groupSum(R,M.representative,M.amount),M.representative,'Expected Amount',true),0)}root.append(grid)}
  function renderCustomers(){const root=document.getElementById('customersContent'),M=CRM.state.mappings,R=CRM.state.filteredRows,col=M.customer||M.company;root.replaceChildren();if(!col)return;const grid=U.dom('div',{class:'analytics-grid'}),metric=U.dom('article',{class:'metric-panel'}),counts=U.groupCount(R,col),repeat=counts.filter(x=>x[1]>1).length,pk=U.dom('div',{class:'panel-kpis'});[['Unique customers',counts.length],['Repeat customers',repeat],['Avg visits',counts.length?R.length/counts.length:0],['With issues',M.issue?new Set(R.filter(r=>!U.isBlank(r[M.issue])).map(r=>U.cleanText(r[col])).filter(Boolean)).size:0]].forEach(([l,v])=>{const a=U.dom('article');a.append(U.dom('span',{text:l}),U.dom('strong',{text:Number.isInteger(v)?U.formatNumber(v):U.formatNumber(v,1)}));pk.append(a)});metric.append(pk);grid.append(metric,entityRankingContent(col));root.append(grid)}
  function renderOpportunities(){const root=document.getElementById('opportunitiesContent'),M=CRM.state.mappings,R=CRM.state.filteredRows;root.replaceChildren();if(!M.amount)return;const vals=amountValues(),grid=U.dom('div',{class:'analytics-grid'}),metric=U.dom('article',{class:'metric-panel'}),pk=U.dom('div',{class:'panel-kpis'}),sum=vals.reduce((a,b)=>a+b,0);[['Potential value',U.compactNumber(sum)],['Valued records',vals.length],['Average',vals.length?U.compactNumber(sum/vals.length):'—'],['Median',vals.length?U.compactNumber(U.median(vals)):'—']].forEach(([l,v])=>{const a=U.dom('article');a.append(U.dom('span',{text:l}),U.dom('strong',{text:String(v)}));pk.append(a)});metric.append(pk);grid.append(metric);if(M.representative){const c=chartCard('Potential by representative','Expected amount only','oppRep');c.className='chart-card wide';grid.append(c);setTimeout(()=>CRM.charts.horizontalBar('oppRep',U.groupSum(R,M.representative,M.amount),M.representative,'Expected Amount',true),0)}if(M.date){const c=chartCard('Potential over time','Only records containing expected amount','oppTime');c.className='chart-card wide';grid.append(c);setTimeout(()=>CRM.charts.moneyTimeline('oppTime',R,M.date,M.amount),0)}root.append(grid)}
  function renderLocations(){const root=document.getElementById('locationsContent'),M=CRM.state.mappings,R=CRM.state.filteredRows;root.replaceChildren();if(!M.location)return;const grid=U.dom('div',{class:'analytics-grid'}),c=chartCard('Visits by location','Ranked geographic activity','locRank');c.className='chart-card wide';grid.append(c);setTimeout(()=>CRM.charts.horizontalBar('locRank',U.groupCount(R,M.location),M.location,'Records'),0);grid.append(entityRankingContent(M.location));root.append(grid)}
  function renderQuality(){const root=document.getElementById('qualityContent'),S=CRM.state;root.replaceChildren();const g=U.dom('div',{class:'quality-grid'}),totalCells=S.rows.length*S.columns.length,missing=S.profile.reduce((s,p)=>s+p.missing,0),avg=S.profile.length?S.profile.reduce((s,p)=>s+(100-p.missingPct),0)/S.profile.length:0;[['Rows',S.rows.length],['Columns',S.columns.length],['Missing cells',missing],['Completeness',U.formatPercent(avg,1)]].forEach(([l,v])=>{const a=U.dom('article',{class:'quality-card'});a.append(U.dom('span',{text:l}),U.dom('strong',{text:typeof v==='number'?U.formatNumber(v):String(v)}));g.append(a)});const list=U.dom('div',{class:'quality-columns'});S.profile.slice().sort((a,b)=>b.missingPct-a.missingPct).forEach(p=>{const row=U.dom('div',{class:'quality-row'}),track=U.dom('div',{class:'quality-track'});track.append(U.dom('i',{style:`width:${100-p.missingPct}%`}));row.append(U.dom('strong',{text:p.displayName,title:p.name}),U.dom('span',{text:p.type}),U.dom('span',{text:`${p.nonEmpty} / ${p.records} populated`}),track);list.append(row)});g.append(list);root.append(g)}
  function renderSection(name){if(name==='overview')renderOverview();if(name==='activity')renderActivity();if(name==='representatives')renderRepresentatives();if(name==='customers')renderCustomers();if(name==='opportunities')renderOpportunities();if(name==='locations')renderLocations();if(name==='quality')renderQuality()}
  function renderFilters(){const root=document.getElementById('filterControls'),S=CRM.state;root.replaceChildren();const filterCols=CRM.profiler.suitableFilters(S.profile,S.mappings);filterCols.forEach(col=>{const p=S.profile.find(x=>x.name===col),block=U.dom('section',{class:'filter-block'}),head=U.dom('div',{class:'filter-title'});head.append(U.dom('strong',{text:p.displayName}),U.dom('span',{text:`${p.uniqueCount} values`}));block.append(head);const counts=CRM.filters.optionCounts(col),opts=U.dom('div',{class:'filter-options'});if(counts.length>8){const search=U.dom('input',{class:'filter-search',type:'search',placeholder:'Search options…','aria-label':`Search ${p.displayName}`});search.addEventListener('input',()=>{const q=U.normalizeHeader(search.value);[...opts.children].forEach(el=>el.hidden=q&&!U.normalizeHeader(el.dataset.value).includes(q))});block.append(search)}counts.forEach(([value,count])=>{const lab=U.dom('label',{class:'filter-option',dataset:{value}}),cb=U.dom('input',{type:'checkbox',checked:!!S.filters[col]?.has(value)});cb.addEventListener('change',()=>CRM.filters.toggle(col,value));const span=U.dom('span',{text:value,title:value});span.dir=U.detectDirection(value);lab.append(cb,span,U.dom('b',{text:U.formatNumber(count)}));opts.append(lab)});block.append(opts);root.append(block)})}
  function datePresetButtons(){const root=document.getElementById('datePresets'),S=CRM.state;root.replaceChildren();if(!S.mappings.date)return;const today=new Date();today.setHours(0,0,0,0);const presets=[['All Time',null],['Today',[today,today]],['Yesterday',[new Date(today.getTime()-86400000),new Date(today.getTime()-86400000)]],['Last 7 Days',[new Date(today.getTime()-6*86400000),today]],['Last 30 Days',[new Date(today.getTime()-29*86400000),today]],['This Month',[new Date(today.getFullYear(),today.getMonth(),1),today]],['Previous Month',[new Date(today.getFullYear(),today.getMonth()-1,1),new Date(today.getFullYear(),today.getMonth(),0)]]];presets.forEach(([label,range])=>{const b=U.dom('button',{class:`date-preset ${S.dateFilter?.label===label?'active':''}`,type:'button',text:label});b.addEventListener('click',()=>range?CRM.filters.setDate(range[0],range[1],label):CRM.filters.setDate(null,null));root.append(b)});const custom=U.dom('div',{class:'date-custom'}),s=U.dom('input',{type:'date','aria-label':'Custom start date'}),e=U.dom('input',{type:'date','aria-label':'Custom end date'});const apply=()=>{CRM.filters.setDate(s.value?new Date(`${s.value}T00:00:00`):null,e.value?new Date(`${e.value}T00:00:00`):null,'Custom Range')};s.addEventListener('change',apply);e.addEventListener('change',apply);custom.append(s,e);root.append(custom)}
  function updateFilterBar(){const S=CRM.state,bar=document.getElementById('activeFilterBar'),chips=document.getElementById('activeChips'),n=CRM.filters.activeCount();document.getElementById('filterCountBadge').textContent=n;document.getElementById('resultCountText').textContent=`${U.formatNumber(S.rows.length)} Records → ${U.formatNumber(S.filteredRows.length)} Matching`;bar.hidden=n===0;chips.replaceChildren();for(const [col,set] of Object.entries(S.filters)){for(const val of set){const p=S.profile.find(x=>x.name===col),chip=U.dom('span',{class:'filter-chip'});chip.append(U.dom('span',{text:`${p?.displayName||col}: ${val}`}),U.dom('button',{type:'button',text:'×','aria-label':`Remove ${val}`}));chip.querySelector('button').addEventListener('click',()=>CRM.filters.toggle(col,val));chips.append(chip)}}if(S.dateFilter){const c=U.dom('span',{class:'filter-chip'});c.append(U.dom('span',{text:S.dateFilter.label}),U.dom('button',{type:'button',text:'×'}));c.querySelector('button').addEventListener('click',()=>CRM.filters.setDate(null,null));chips.append(c)}if(S.searchQuery){const c=U.dom('span',{class:'filter-chip'});c.append(U.dom('span',{text:`Search: ${S.searchQuery}`}),U.dom('button',{type:'button',text:'×'}));c.querySelector('button').addEventListener('click',()=>CRM.filters.setSearch(''));chips.append(c)}}
  function openDetail(row){const root=document.getElementById('detailContent'),M=CRM.state.mappings;root.replaceChildren();const actions=U.dom('div',{class:'detail-actions'});if(M.phone&&U.safePhone(row[M.phone]))actions.append(U.dom('a',{class:'detail-action',href:`tel:${U.safePhone(row[M.phone])}`,text:'Call'}));if(M.email&&U.safeEmail(row[M.email]))actions.append(U.dom('a',{class:'detail-action',href:`mailto:${U.safeEmail(row[M.email])}`,text:'Email'}));if(M.map&&U.safeUrl(row[M.map]))actions.append(U.dom('a',{class:'detail-action',href:U.safeUrl(row[M.map]),target:'_blank',rel:'noopener noreferrer',text:'Open Location ↗'}));if(actions.childElementCount)root.append(actions);const priority=[M.customer,M.company,M.representative,M.date,M.location,M.purpose,M.amount,M.product,M.quantity,M.notes,M.issue,M.phone,M.email,M.map].filter(Boolean),ordered=[...new Set([...priority,...CRM.state.columns])];const groups=[['CRM Context',ordered.filter(c=>[M.customer,M.company,M.representative,M.date,M.location,M.purpose,M.amount].includes(c))],['Visit Details',ordered.filter(c=>[M.product,M.quantity,M.notes,M.issue].includes(c))],['Contact & Links',ordered.filter(c=>[M.phone,M.email,M.map].includes(c))],['Additional Fields',ordered.filter(c=>![M.customer,M.company,M.representative,M.date,M.location,M.purpose,M.amount,M.product,M.quantity,M.notes,M.issue,M.phone,M.email,M.map].includes(c))]];groups.forEach(([title,cols])=>{const filled=cols.filter(c=>!U.isBlank(row[c]));if(!filled.length)return;const sec=U.dom('section',{class:'detail-group'});sec.append(U.dom('h3',{text:title}));const dl=U.dom('dl');filled.forEach(c=>{const p=CRM.state.profile.find(x=>x.name===c),wrap=U.dom('div',{class:'detail-field'}),dd=U.dom('dd',{text:U.formatByMeta(row[c],p)});dd.dir=U.detectDirection(row[c]);wrap.append(U.dom('dt',{text:p?.displayName||c}),dd);dl.append(wrap)});sec.append(dl);root.append(sec)});document.getElementById('detailDrawerBackdrop').hidden=false}
  function renderFieldMappings(){const root=document.getElementById('fieldMappings'),S=CRM.state;root.replaceChildren();const concepts=[['date','Primary Date'],['representative','Representative'],['customer','Customer'],['company','Company / Project'],['location','Location'],['purpose','Visit Purpose'],['amount','Expected Amount'],['product','Product'],['quantity','Quantity'],['notes','Notes'],['issue','Issues'],['phone','Phone'],['email','Email'],['map','Map URL']];concepts.forEach(([key,label])=>{const row=U.dom('div',{class:'mapping-row'}),sel=U.dom('select',{dataset:{mapping:key}});sel.append(U.dom('option',{value:'',text:'Not mapped'}));S.profile.forEach(p=>sel.append(U.dom('option',{value:p.name,text:p.displayName,selected:S.mappings[key]===p.name})));const confidence=S.mappings[key]?S.profile.find(p=>p.name===S.mappings[key])?.semanticScores?.[key]||0:0;row.append(U.dom('label',{text:label}),sel,U.dom('span',{text:S.mappings[key]?`${Math.round(confidence*100)}% semantic`:'Optional'}));root.append(row)})}
  function saveFieldMappings(){const next={...CRM.state.mappings};document.querySelectorAll('#fieldMappings select').forEach(s=>{if(s.value)next[s.dataset.mapping]=s.value;else delete next[s.dataset.mapping]});CRM.state.mappings=next;document.getElementById('fieldsModal').hidden=true;renderAll();renderFilters();datePresetButtons();CRM.toast('Field mappings updated.','success')}
  function renderSearchPreview(){const root=document.getElementById('searchPreview'),q=document.getElementById('globalSearchInput').value,S=CRM.state;root.replaceChildren();if(!q.trim()){root.append(U.dom('div',{class:'empty-card',text:'Search across customers, representatives, locations, notes, products and other text fields.'}));return}const norm=U.normalizeHeader(q),cols=S.profile.filter(p=>['person/name','company/customer','geographic/location','product','long text','free text','categorical'].includes(p.type)).map(p=>p.name),hits=S.rows.filter(r=>cols.some(c=>U.normalizeHeader(r[c]).includes(norm))).slice(0,10);hits.forEach(r=>{const first=cols.find(c=>U.normalizeHeader(r[c]).includes(norm)),el=U.dom('div',{class:'search-result',tabIndex:0}),left=U.dom('div');left.append(U.dom('strong',{text:U.cleanText(r[first])}),U.dom('small',{text:first}));el.append(left,U.dom('small',{text:`Row ${r.__rowIndex}`}));el.addEventListener('click',()=>{CRM.filters.setSearch(q);document.getElementById('searchModal').hidden=true;showSection('explorer')});root.append(el)});if(!hits.length)root.append(U.dom('div',{class:'empty-card',text:'No matching records.'}))}
  function renderAll(){renderNav();updateFilterBar();renderSection(CRM.state.activeSection);document.getElementById('recordBadge').textContent=`${U.formatNumber(CRM.state.rows.length)} records`;document.getElementById('overviewSubtitle').textContent=`${U.formatNumber(CRM.state.filteredRows.length)} matching records · ${U.formatNumber(CRM.state.columns.length)} detected fields`}
  CRM.events.addEventListener('filters:changed',()=>{updateFilterBar();renderFilters();datePresetButtons();renderSection(CRM.state.activeSection);if(CRM.state.activeSection==='explorer')CRM.table.render()});
  CRM.dashboard={renderAll,renderNav,showSection,renderFilters,datePresetButtons,openDetail,renderFieldMappings,saveFieldMappings,renderSearchPreview};
})();
