(function(){
  const CRM=window.CRM=window.CRM||{},U=CRM.utils;
  function ensureLibraries(){if(typeof XLSX==='undefined')throw new Error('Excel library could not be loaded. Check your internet connection and reload the page.')}
  async function readFile(file){ensureLibraries();const data=await file.arrayBuffer();let wb;try{wb=XLSX.read(data,{type:'array',cellDates:true,dense:false})}catch(e){throw new Error('This workbook could not be read. It may be damaged, encrypted, or password-protected.')}if(!wb.SheetNames?.length)throw new Error('The workbook does not contain any worksheets.');return wb}
  function scoreSheet(ws){const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true,blankrows:false});if(!matrix.length)return{score:-1,rows:0,cols:0,headerRow:0};let best={score:-1,headerRow:0};for(let i=0;i<Math.min(matrix.length,12);i++){const row=matrix[i]||[];const vals=row.filter(v=>!U.isBlank(v));const text=vals.filter(v=>typeof v==='string').length;const uniq=new Set(vals.map(U.cleanText)).size;const score=vals.length*4+text*2+uniq-Math.max(0,i-2);if(score>best.score)best={score,headerRow:i}}const cols=Math.max(...matrix.slice(best.headerRow,best.headerRow+10).map(r=>r?.length||0),0);const dataRows=matrix.slice(best.headerRow+1).filter(r=>r&&r.some(v=>!U.isBlank(v))).length;return{score:best.score+Math.min(dataRows,50),rows:dataRows,cols,headerRow:best.headerRow}}
  function getSheetCandidates(wb){return wb.SheetNames.map(name=>({name,...scoreSheet(wb.Sheets[name])})).sort((a,b)=>b.score-a.score)}
  function normalizeHeaders(rawHeaders){const used=new Map();return rawHeaders.map((h,i)=>{let base=U.cleanText(h)||`Column ${i+1}`;const key=base.toLowerCase();const count=(used.get(key)||0)+1;used.set(key,count);return count>1?`${base} (${count})`:base})}
  function parseSheet(wb,name,headerRowHint){const ws=wb.Sheets[name];if(!ws)throw new Error('The selected worksheet no longer exists.');const matrix=XLSX.utils.sheet_to_json(ws,{header:1,defval:null,raw:true,blankrows:false});if(!matrix.length)throw new Error('The selected worksheet is empty.');const hint=Number.isInteger(headerRowHint)?headerRowHint:scoreSheet(ws).headerRow;const headers=normalizeHeaders(matrix[hint]||[]);const rows=[];for(let i=hint+1;i<matrix.length;i++){const arr=matrix[i]||[];if(!arr.some(v=>!U.isBlank(v)))continue;const obj={__rowIndex:i+1,__id:`row-${i+1}`};headers.forEach((h,j)=>obj[h]=arr[j]??null);rows.push(obj)}if(!rows.length)throw new Error('No data rows were detected beneath the worksheet header.');return{rows,headers,headerRow:hint}}
  CRM.excel={readFile,getSheetCandidates,parseSheet};
})();
