(function(){
  const CRM=window.CRM=window.CRM||{},U=CRM.utils;
  function getVisible(){const S=CRM.state;const cols=S.columns.filter(c=>S.visibleColumns.has(c));return cols.length?cols:S.columns.slice(0,8)}
  function sortRows(rows){const {column,direction}=CRM.state.sort;if(!column)return rows;const meta=CRM.state.profile.find(p=>p.name===column);return [...rows].sort((a,b)=>{let x=a[column],y=b[column],cmp=0;if(['numeric','monetary','percentage','quantity'].includes(meta?.type)){x=U.numberValue(x);y=U.numberValue(y);cmp=(Number.isFinite(x)?x:-Infinity)-(Number.isFinite(y)?y:-Infinity)}else if(['date','datetime'].includes(meta?.type)){x=U.parseDate(x)?.getTime()||0;y=U.parseDate(y)?.getTime()||0;cmp=x-y}else cmp=U.cleanText(x).localeCompare(U.cleanText(y),undefined,{numeric:true,sensitivity:'base'});return direction==='asc'?cmp:-cmp})}
  function render(){const root=document.getElementById('dataExplorer');if(!root)return;root.replaceChildren();const S=CRM.state,rows=sortRows(S.filteredRows),cols=getVisible(),pages=Math.max(1,Math.ceil(rows.length/S.pagination.rowsPerPage));S.pagination.page=Math.min(S.pagination.page,pages);const start=(S.pagination.page-1)*S.pagination.rowsPerPage,visible=rows.slice(start,start+S.pagination.rowsPerPage);
    const shell=U.dom('div',{class:'table-shell'});const toolbar=U.dom('div',{class:'table-toolbar'});const input=U.dom('input',{type:'search',placeholder:'Search within current results…',value:S.searchQuery,'aria-label':'Search filtered CRM records'});input.addEventListener('input',U.debounce(e=>CRM.filters.setSearch(e.target.value),160));toolbar.append(input,U.dom('div',{class:'table-count',text:`${U.formatNumber(rows.length)} matching rows · ${U.formatNumber(cols.length)} visible columns`}));
    const scroll=U.dom('div',{class:'table-scroll'}),table=U.dom('table',{class:'data-table'}),thead=U.dom('thead'),trh=U.dom('tr');cols.forEach(c=>{const th=U.dom('th',{text:CRM.state.profile.find(p=>p.name===c)?.displayName||c});th.title=c;th.tabIndex=0;const sort=()=>{if(S.sort.column===c)S.sort.direction=S.sort.direction==='asc'?'desc':'asc';else S.sort={column:c,direction:'asc'};render()};th.addEventListener('click',sort);th.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();sort()}});trh.append(th)});thead.append(trh);table.append(thead);const tbody=U.dom('tbody');visible.forEach(r=>{const tr=U.dom('tr',{tabIndex:0});const open=()=>CRM.dashboard.openDetail(r);tr.addEventListener('click',open);tr.addEventListener('keydown',e=>{if(e.key==='Enter')open()});cols.forEach(c=>{const meta=S.profile.find(p=>p.name===c);const td=U.dom('td',{text:U.formatByMeta(r[c],meta)});td.dir=U.detectDirection(r[c]);td.classList.add('dir-auto');tr.append(td)});tbody.append(tr)});table.append(tbody);scroll.append(table);shell.append(toolbar,scroll);
    const pag=U.dom('div',{class:'table-pagination'});const select=U.dom('select',{class:'rows-select','aria-label':'Rows per page'});[10,25,50,100].forEach(n=>select.append(U.dom('option',{value:n,text:`${n} rows`,selected:n===S.pagination.rowsPerPage})));select.addEventListener('change',e=>{S.pagination.rowsPerPage=+e.target.value;S.pagination.page=1;render()});const pager=U.dom('div',{class:'pager'}),prev=U.dom('button',{type:'button',text:'‹',disabled:S.pagination.page<=1}),info=U.dom('button',{type:'button',text:`${S.pagination.page} / ${pages}`,disabled:true}),next=U.dom('button',{type:'button',text:'›',disabled:S.pagination.page>=pages});prev.addEventListener('click',()=>{S.pagination.page--;render()});next.addEventListener('click',()=>{S.pagination.page++;render()});pager.append(prev,info,next);pag.append(select,pager);shell.append(pag);root.append(shell)
  }
  function renderColumnSelector(){const root=document.getElementById('columnChecklist');root.replaceChildren();CRM.state.profile.forEach(p=>{const item=U.dom('div',{class:'column-item'});const label=U.dom('label'),cb=U.dom('input',{type:'checkbox',checked:CRM.state.visibleColumns.has(p.name)});cb.addEventListener('change',()=>{cb.checked?CRM.state.visibleColumns.add(p.name):CRM.state.visibleColumns.delete(p.name);render()});label.append(cb,U.dom('span',{text:p.displayName}));item.append(label,U.dom('span',{text:`${p.type} · ${p.nonEmpty}/${p.records}`}));root.append(item)})}
  CRM.table={render,renderColumnSelector,getVisible};
})();
